title: How I do my work with GitHub!
author: @mammamoo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here I will talk about my work with GitHub. Also my results!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
